### ISSUE TITLE
Compare with http://golosknigi.com/page3.html

### ISSUE THREAD

**Issue by paulvi** [vantu5z/RHVoice-dictionary#221]
Hello

Can you comment or compare with other RHVoice disctionary mentioned at http://golosknigi.com/page3.html as "Скачать словари для "Балаболка", "Демагог" и движка RHvoice."

**Comment by vantu5z** [comment]
Hello, @paulvi !
Yes I know about this dictionaries.
Some comments and comparing:
1. Format.
I don't know if it works on pure RHVoice without some application like ("Балаболка", "Демагог").
Think it's not, but not difficult to modify it.
Example:
`ёпрст=ъъQёъъ ъъпэрэсэтQэъъ`
Rules contain `ъъ` on start and end of each word.
2. Expand rules.
We try to write one rule instead of rules for all word forms.
Example:
`авиапочт+ов{ая,ого,ое,ой,ом,ому,ую,ые,ый,ым,ыми,ых}`
It will have 12 rules for each form. Maybe this is better, but I think is not.
3. Already right stress.
RHVoice already have right stress for some words #70 or will have. We have this issue too.
I don't know if they check that huge count of rules, but doubt.
Sometimes it will lead to speed issue.
4. Text preprocessing.
Both dictionaries have this featcher.
But we have standalone dictionaries for RHVoice and separate Preprocessing tool (uses Python).
Look like they use only text preprocessing, so Application used for reading prepare text and puts stress markers according dictionary. So it is not dictionary for RHVoice but it is dictionary for "Балаболка", "Демагог" that used RHVoice.

For comparison you cat test them on some text and say us which is better :)

**Comment by paulvi** [comment]
Good explanation,
I wish I found this dictionary before.

It looks like this is the best dictionary for RHVoice, it should at least referenced within RHVoice pages.

**Comment by velmyshanovnyi** [comment]
> http://golosknigi.com/page3.html as "

golosknigi.com
Истёк срок регистрации домена
